export default [{
  name: '系统首页',
  path: '/index',
  icon: 'el-icon-goods',
  children: []
}, {
  name: '人员管理',
  path: '/person',
  icon: 'el-icon-sold-out',
  children: [{
    name: '人员信息',
    path: '/person/index',
    icon: 'el-icon-menu',
    children: []
  }, {
    name: '人员管理',
    path: '/person/database',
    icon: 'el-icon-menu',
    children: []
  }]
}, {
  name: '识别记录',
  path: '/recognize/index',
  icon: 'el-icon-picture',
  children: []
}, {
  name: '区域管理',
  path: '/region/index',
  icon: 'el-icon-location',
  children: []
}, {
  name: '系统管理',
  path: '/system',
  icon: 'el-icon-tickets',
  children: [{
    name: '系统设置',
    path: '/system/index',
    icon: 'el-icon-tickets',
    children: []
  }, {
    name: '组织管理',
    path: '/system/organization',
    icon: 'el-icon-tickets',
    children: []
  }, {
    name: '账号管理',
    path: '/system/accounts',
    icon: 'el-icon-tickets',
    children: []
  }, {
    name: '角色管理',
    path: '/system/role',
    icon: 'el-icon-tickets',
    children: []
  }]
}];
